### ISSUE TITLE
FileNotFoundError .wig when run --sv

### ISSUE THREAD

**Issue by Sondr11** [J35P312/TIDDIT#23]
Hi.
I try run TIDDIT.py --sv for file bam of nipt data. 
I used command as: python /home/TIDDIT/TIDDIT.py  --sv --bam 'file_to_path_bam' --ref 'file_to_path_hg19.fa'
I recieved error below:
_'Traceback (most recent call last):
  File "/home/TIDDIT/TIDDIT.py", line 91, in <module>
    TIDDIT_calling.cluster(args)
  File "TIDDIT_calling.py", line 207, in TIDDIT_calling.cluster
    coverage_data,span_data=TIDDIT_coverage.coverage(args)
  File "TIDDIT_coverage.py", line 8, in TIDDIT_coverage.coverage
    for line in open(args.o+".wig"):
FileNotFoundError: [Errno 2] No such file or directory: 'output.wig'_
When running, I see it creat two file as: 'output.gc.wig' and  'output.sample.bam'. But I don't see file  'output.wig'
Please help me to fix this problem.
Thank you so much

**Comment by J35P312** [comment]
Hello!
Though luck! I notice you are running an old version of TIDDIT. Old TIDDIT consisted of a C++ module as well as python module. I believe the C++ module crashed; could you send more of the output? That error message should have been printed sometime before the missing file error.

Alternatively, you may try to update TIDDIT to a later version.

It is cool that you are running tiddit on NIPT data! Is the data paired-end data? TIDDIT will only work on paired-end data.
New (> 3.0.0) will probably work on single-end but there are better tools designed for that purpose. Usually NIPT data is too shallow for doing a meaningful paired-end analysis, you may be better off using read depth approaches such as WiseCondorX or CNVkit.

Good luck!

**Comment by Sondr11** [comment]
Thank you so much
